import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CardList from "@/components/CardList";
import {TCard} from "@/types/card";
import {GetServerSideProps, InferGetServerSidePropsType} from "next";

const inter = Inter({ subsets: ["latin"] });

export default function Home({cards}: InferGetServerSidePropsType<typeof getServerSideProps>) {

    const data = [...cards]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CardList cards={data}/>
      </div>
    </>
  );
}

export const getServerSideProps = (async ({query}) => {
    let res = await fetch('http://localhost:5000/api/card')
    if (!res) {
        return {
            redirect: {
                destination: '/',
                permanent: false,
            },
        }
    }
    const cards: TCard[] = await res.json()
    return { props: { cards } }
}) satisfies GetServerSideProps<{ cards: TCard[] }>


